### ISSUE TITLE
number of Centroids is 0 when maxIterations > 0

### ISSUE THREAD

**Issue by RadovanF** [berak/opencv_smallfry#2]
Hi,

first of all, i would like to thank for your source codes. 
However, the kmajority works (for me) when the maxIterations = 0.
In the case that the maxIterations > 0 and the computeCentroids method is called, the elements of return centroids matrix are zero.  

Do I somethings wrong?

Many thanks and Best regards,
midwej

**Comment by berak** [comment]
thanks for your feedback, let me enquire .. (when in doubt, assume, that the error is on my side !)

i might have broken something, [taking the code from here](https://github.com/gantzer89/VLRPipeline/tree/master/KMajorityLib)

**Comment by berak** [comment]
bug confirmed ;) i never realized, i assumed, the TermCriteria had some sensible default. (that's bug #1)

[this](https://github.com/berak/opencv_smallfry/blob/ec83924fa63a5753e83f3e3f89d9906d232ddcde/bow/BOWKmajorityTrainer.cpp#L64) must have rows, not cols., [see commit](https://github.com/berak/opencv_smallfry/commit/27260e3a49a528f70baade0003bed39803431437#diff-31525372e7352d070ac49bd6ccb43ff5R63) (apologies,  commit is pretty noisy)

**Comment by RadovanF** [comment]
With rows, the source code looks like it works.
Thanks for your fast reply.

**Comment by berak** [comment]
nice to hear that !

just curious, what are you doing with it ?

**Comment by RadovanF** [comment]
At this moment I am working on recognition of driver behavior inside the car cockpit. I know how to use SIFT, SURF with BoW model combined with opencv. However, I would like to explore binary features (e.g. ORB, BRIEF) and comprate the binary features with SURF, SIFT using BoW for my scientific work. I started with hierarchical clustering and Hamming distance, unfortunately there is bug in opencv and kmajority method is a next possibility. 

If you are interested in my work (or if you have some scientific papers related to the object recognition/detection) please do not hesitate to contact me.

**Comment by berak** [comment]
best of luck with it ;)
